### ISSUE TITLE
What a great project, but is it technically legal?

### ISSUE THREAD

**Issue by will-stone** [camden/rulebooks#23]
Hi. I really like the idea of the project, and kudos on the work so far. However can you please add a section on the site as to how this is legal? It doesn’t quite feel right; getting people to copy rules from games and host them here.

**Comment by camden** [comment]
Hey Will! Thanks for the feedback.

I’m not sure about the legality of hosting these rules. I’ve been doing some research about the best way to ask for permission from publishers. In the meantime, if any publishers ask me to take down a rulebook, I of course will comply. 

FWIW, I’m not in any way making money from Rulebook.io - not that that would hold up in a court of law, but my heart *is* in the right place.

My vision for Rulebook.io is a publisher-supported, free-to-use, rulebook wiki. Please let me know if you have any suggestions to reach this end in a legal & ethical manner.

- Cam

**Comment by will-stone** [comment]
As long as it's easy to search and community-maintain, then people will come. I really don't have the knowledge to offer legal counsel, I just thought this should be something that's clearly prominent on the site.
